name: Feature Request
description: Suggest a new feature or enhancement for the mod.
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see added.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?
      placeholder: Explain why this feature would be useful.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should work?
      placeholder: Describe how you envision the feature working.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions or workarounds you've thought about.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Mockups
      description: If applicable, add screenshots or mockups to help explain your feature request.
      placeholder: Drag and drop images here or paste image URLs.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request.
    validations:
      required: false
